apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: web-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: static-content
          persistentVolumeClaim:
            claimName: static-pvc

