apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/web-content"  # Ruta en tu máquina local montada con minikube mount
  persistentVolumeReclaimPolicy: Retain

